service: sampleJavaLayer

provider:
  name: aws
  runtime: java8
  timeout: 30

  stage: dev
  region: ap-northeast-1

layers:
  javaLibraries:
    package:
      artifact: build/distributions/libraries-1.0-SNAPSHOT.zip
    name: dev-javalibraries
    compatibleRuntimes:
    - java8
    allowedAccounts:
    - '*'

resources:
  Outputs:
    JavaLibrariesLayerExport:
      Value:
        Ref: JavaLibrariesLambdaLayer
      Export:
        Name: JavaLibrariesLambdaLayer